# -*- coding: mbcs -*-
#
# Abaqus/CAE Release 2017 replay file
# Internal Version: 2016_09_27-14.54.59 126836
# Run by cbonsignore on Tue Apr 04 12:39:29 2017
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=256.261901855469, 
    height=112.685722351074)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from caeModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
Mdb()
#: A new model database has been created.
#: The model "Model-1" has been created.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
mdb.openAuxMdb(
    pathName='C:/AbaqusTemp/smst17-elp-frame/AVFrame-OSS-pulsatile-2017-02-14.cae')
mdb.copyAuxMdbModel(fromName='AV-OSS-pulsatile-9%-V25mm', 
    toName='AV-OSS-pulsatile-9%-V25mm')
mdb.closeAuxMdb()
session.openOdb(
    'C:/Users/cbonsignore.NITINOL/Documents/GitHub/nitinol-design-concepts/102-open-frame-shape-set/shape-set.odb')
#: Model: C:/Users/cbonsignore.NITINOL/Documents/GitHub/nitinol-design-concepts/102-open-frame-shape-set/shape-set.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     5
#: Number of Meshes:             5
#: Number of Element Sets:       6
#: Number of Node Sets:          12
#: Number of Steps:              9
odb = session.odbs['C:/Users/cbonsignore.NITINOL/Documents/GitHub/nitinol-design-concepts/102-open-frame-shape-set/shape-set.odb']
odb.close()
del mdb.models['Model-1']
p = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['CONCEPT-D101-AS-CUT']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['AV-OSS-pulsatile-9%-V25mm'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    optimizationTasks=OFF, geometricRestrictions=OFF, stopConditions=OFF)
session.viewports['Viewport: 1'].enableMultipleColors()
session.viewports['Viewport: 1'].setColor(initialColor='#BDBDBD')
cmap=session.viewports['Viewport: 1'].colorMappings['Part instance']
session.viewports['Viewport: 1'].setColor(colorMapping=cmap)
session.viewports['Viewport: 1'].disableMultipleColors()
session.viewports['Viewport: 1'].setColor(globalTranslucency=True)
session.viewports['Viewport: 1'].view.setValues(nearPlane=172.061, 
    farPlane=294.153, width=95.7325, height=53.4671, viewOffsetX=-1.92014, 
    viewOffsetY=0.20719)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['CONCEPT-D101-AS-CUT']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['CONCEPT-D101-AS-CUT']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=OFF, 
    engineeringFeatures=OFF, mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
a = mdb.models['AV-OSS-pulsatile-9%-V25mm'].rootAssembly
a.regenerate()
a = mdb.models['AV-OSS-pulsatile-9%-V25mm'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='diastole-03')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='crimp-10mm')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, interactions=ON, constraints=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=ON, 
    engineeringFeatures=ON, mesh=OFF)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=OFF)
p = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['CONCEPT-D101-AS-CUT']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['AV-OSS-pulsatile-9%-V25mm'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='Initial')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, interactions=OFF, constraints=OFF, 
    engineeringFeatures=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, interactions=ON, constraints=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    step='deploy-annulus-25mm')
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=OFF, 
    engineeringFeatures=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['chamber']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['chamber']
s = p.features['Shell revolve-1'].sketch
mdb.models['AV-OSS-pulsatile-9%-V25mm'].ConstrainedSketch(name='__edit__', 
    objectToCopy=s)
s1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell revolve-1'], filter=COPLANAR_EDGES)
s1.unsetPrimaryObject()
del mdb.models['AV-OSS-pulsatile-9%-V25mm'].sketches['__edit__']
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['chamber']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['crimp-cyl-full']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['crimp-cyl-full']
s = p.features['Shell extrude-1'].sketch
mdb.models['AV-OSS-pulsatile-9%-V25mm'].ConstrainedSketch(name='__edit__', 
    objectToCopy=s)
s2 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell extrude-1'], filter=COPLANAR_EDGES)
s2.unsetPrimaryObject()
del mdb.models['AV-OSS-pulsatile-9%-V25mm'].sketches['__edit__']
p1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['chamber']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['chamber']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['AV-OSS-pulsatile-9%-V25mm'].parts['chamber']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
openMdb(
    pathName='C:/Users/cbonsignore.NITINOL/Documents/GitHub/nitinol-design-concepts/102-open-frame-shape-set/open-frame-shape-set.cae')
#: The model database "C:\Users\cbonsignore.NITINOL\Documents\GitHub\nitinol-design-concepts\102-open-frame-shape-set\open-frame-shape-set.cae" has been opened.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
p = mdb.models['shape-set-AV-OSS-D101-01'].parts['Concept-D101-as-cut']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p1 = mdb.models['shape-set-AV-OSS-D101-01'].parts['exp-cyl']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
a = mdb.models['shape-set-AV-OSS-D101-01'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=OFF, 
    constraints=OFF, connectors=OFF, engineeringFeatures=OFF)
session.viewports['Viewport: 1'].enableMultipleColors()
session.viewports['Viewport: 1'].setColor(initialColor='#BDBDBD')
cmap=session.viewports['Viewport: 1'].colorMappings['Part instance']
session.viewports['Viewport: 1'].setColor(colorMapping=cmap)
session.viewports['Viewport: 1'].disableMultipleColors()
session.viewports['Viewport: 1'].view.setValues(nearPlane=218.504, 
    farPlane=357.372, width=94.5616, height=52.8132, viewOffsetX=8.6934, 
    viewOffsetY=6.34594)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=OFF, 
    engineeringFeatures=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p1 = mdb.models['shape-set-AV-OSS-D101-01'].parts['Concept-D101-as-cut']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
session.viewports['Viewport: 1'].enableMultipleColors()
session.viewports['Viewport: 1'].setColor(initialColor='#BDBDBD')
cmap=session.viewports['Viewport: 1'].colorMappings['Part']
session.viewports['Viewport: 1'].setColor(colorMapping=cmap)
session.viewports['Viewport: 1'].disableMultipleColors()
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
session.viewports['Viewport: 1'].view.setValues(nearPlane=114.409, 
    farPlane=152.66, width=8.876, height=4.97286, viewOffsetX=-14.1075, 
    viewOffsetY=8.2957)
session.viewports['Viewport: 1'].view.setValues(nearPlane=114.47, 
    farPlane=152.6, width=8.8807, height=4.97549, viewOffsetX=-15.9343, 
    viewOffsetY=9.37365)
session.viewports['Viewport: 1'].view.setValues(nearPlane=114.763, 
    farPlane=152.307, width=6.53425, height=3.66087, viewOffsetX=-16.5319, 
    viewOffsetY=9.65989)
session.viewports['Viewport: 1'].view.setValues(nearPlane=114.721, 
    farPlane=152.348, width=6.53186, height=3.65954, viewOffsetX=-16.1362, 
    viewOffsetY=9.35267)
session.viewports['Viewport: 1'].view.setValues(nearPlane=114.839, 
    farPlane=152.231, width=5.10499, height=2.86012, viewOffsetX=-16.4892, 
    viewOffsetY=9.45503)
session.viewports['Viewport: 1'].view.setValues(nearPlane=114.873, 
    farPlane=152.196, width=5.10652, height=2.86097, viewOffsetX=-16.6866, 
    viewOffsetY=9.75069)
session.viewports['Viewport: 1'].view.setValues(width=4.80014, height=2.68932, 
    viewOffsetX=-16.734, viewOffsetY=9.75534)
session.viewports['Viewport: 1'].view.setValues(nearPlane=114.906, 
    farPlane=152.163, width=4.8015, height=2.69008, viewOffsetX=-16.2677, 
    viewOffsetY=10.0558)
p1 = mdb.models['shape-set-AV-OSS-D101-01'].parts['large-dia-sleeve']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['shape-set-AV-OSS-D101-01'].parts['mandrel-core']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
session.viewports['Viewport: 1'].view.setValues(nearPlane=107.037, 
    farPlane=185.993, width=89.4549, height=50.1179, cameraPosition=(46.7246, 
    50.1797, 133.67), cameraUpVector=(-0.518896, 0.750401, -0.409446), 
    cameraTarget=(0.84629, 10.8074, 0.846274))
session.viewports['Viewport: 1'].view.setValues(nearPlane=105.768, 
    farPlane=189.991, width=88.3941, height=49.5236, cameraPosition=(120.047, 
    -43.2881, 65.93), cameraUpVector=(-0.0768788, 0.977032, 0.198744), 
    cameraTarget=(1.13638, 10.4376, 0.578275))
session.viewports['Viewport: 1'].view.setValues(nearPlane=106.306, 
    farPlane=190.713, width=88.8436, height=49.7754, cameraPosition=(42.9999, 
    -93.1861, 95.0693), cameraUpVector=(0.206157, 0.902934, 0.377106), 
    cameraTarget=(0.123434, 9.78159, 0.961372))
session.viewports['Viewport: 1'].view.setValues(nearPlane=105.996, 
    farPlane=192.204, width=88.5849, height=49.6305, cameraPosition=(-65.7374, 
    -98.4896, 74.7808), cameraUpVector=(0.494422, 0.593009, 0.635521), 
    cameraTarget=(-1.76143, 9.68966, 0.60969))
p = mdb.models['shape-set-AV-OSS-D101-01'].parts['mandrel-core']
s = p.features['3D Analytic rigid shell-1'].sketch
mdb.models['shape-set-AV-OSS-D101-01'].ConstrainedSketch(name='__edit__', 
    objectToCopy=s)
s1 = mdb.models['shape-set-AV-OSS-D101-01'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['3D Analytic rigid shell-1'], filter=COPLANAR_EDGES)
s1.unsetPrimaryObject()
del mdb.models['shape-set-AV-OSS-D101-01'].sketches['__edit__']
a = mdb.models['shape-set-AV-OSS-D101-01'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    adaptiveMeshConstraints=ON)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=ON, 
    constraints=ON, connectors=ON, engineeringFeatures=ON, 
    adaptiveMeshConstraints=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, interactions=OFF, constraints=OFF, 
    engineeringFeatures=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='expand-14mm')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF, adaptiveMeshConstraints=ON)
Mdb()
#: A new model database has been created.
#: The model "Model-1" has been created.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
a = mdb.models['Model-1'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.openAuxMdb(
    pathName='C:/AbaqusTemp/smst17-elp-frame/AVFrame-OSS-pulsatile-01.cae')
mdb.openAuxMdb(
    pathName='C:/AbaqusTemp/smst17-elp-frame/AVFrame-OSS-pulsatile-2017-02-14.cae')
mdb.copyAuxMdbModel(fromName='AV-OSS-pulsatile-9%-V25mm', 
    toName='AV-OSS-pulsatile-9%-V25mm')
mdb.closeAuxMdb()
del mdb.models['Model-1']
a = mdb.models['AV-OSS-pulsatile-9%-V25mm'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].enableMultipleColors()
session.viewports['Viewport: 1'].setColor(initialColor='#BDBDBD')
cmap=session.viewports['Viewport: 1'].colorMappings['Part instance']
session.viewports['Viewport: 1'].setColor(colorMapping=cmap)
session.viewports['Viewport: 1'].disableMultipleColors()
mdb.saveAs(
    pathName='C:/Users/cbonsignore.NITINOL/Documents/GitHub/nitinol-design-concepts/103-open-frame-fatigue/open-frame-fatigue')
#: The model database has been saved to "C:\Users\cbonsignore.NITINOL\Documents\GitHub\nitinol-design-concepts\103-open-frame-fatigue\open-frame-fatigue.cae".
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='systole-01')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='crimp-10mm')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='systole-01')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    adaptiveMeshConstraints=OFF)
mdb.models.changeKey(fromName='AV-OSS-pulsatile-9%-V25mm', 
    toName='open-frame-fatigue-v25mm-9pct')
a = mdb.models['open-frame-fatigue-v25mm-9pct'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.save()
#: The model database has been saved to "C:\Users\cbonsignore.NITINOL\Documents\GitHub\nitinol-design-concepts\103-open-frame-fatigue\open-frame-fatigue.cae".
mdb.Job(name='open-frame-fatigue-v25mm-9pct', 
    model='open-frame-fatigue-v25mm-9pct', description='', type=ANALYSIS, 
    atTime=None, waitMinutes=0, waitHours=0, queue=None, memory=90, 
    memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, multiprocessingMode=DEFAULT, numCpus=1, 
    numGPUs=0)
mdb.jobs['open-frame-fatigue-v25mm-9pct'].writeInput(consistencyChecking=OFF)
#: The job input file has been written to "open-frame-fatigue-v25mm-9pct.inp".
mdb.save()
#: The model database has been saved to "C:\Users\cbonsignore.NITINOL\Documents\GitHub\nitinol-design-concepts\103-open-frame-fatigue\open-frame-fatigue.cae".
